// Generates api/_systemPrompt.ts from src/assistant/knowledge.ts, so the serverless chat function
// is self-contained. Runs automatically as part of `npm run build`.
import { writeFileSync } from 'node:fs'
import { buildSystemPrompt } from '../src/assistant/knowledge'

const output = `// Generated by scripts/build-assistant-prompt.ts from src/assistant/knowledge.ts. Do not edit by hand.
export const SYSTEM_PROMPT = ${JSON.stringify(buildSystemPrompt())}
`

writeFileSync(new URL('../api/_systemPrompt.ts', import.meta.url), output)
console.log('api/_systemPrompt.ts updated')
